name: Build, Lint, Coverage & Release

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on version tags: v0.2.3, v1.0.0, etc.

jobs:
  build-and-release:
    runs-on: self-hosted

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Lint code
      - name: Lint code
        run: npm run lint

      # 5. Run tests and collect coverage
      - name: Run tests and collect coverage
        env:
          ROKU_DEV_TARGET: ${{ secrets.ROKU_DEV_TARGET }}
          ROKU_DEV_PASS: ${{ secrets.ROKU_DEV_PASS }}
        run: npm run collect-coverage

      # 6. Upload coverage to Coveralls
      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: coverage.lcov
          base-path: src

      # 7. Build and create Roku package (ZIP)
      - name: Build and create Roku package
        run: npx bsc --project bsconfig.json --createPackage=true

      # 8. Create GitHub Release and upload package
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: out/*.zip
          generate_release_notes: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
