name: Build, Lint, Coverage & Release

on:
  push:
    branches: [ main ]          # ← badge frissítés
    tags:
      - 'v*.*.*'                # ← release
  pull_request:                 # ← PR patch coverage
    branches: [ main ]

jobs:
  build-and-release:
    runs-on: self-hosted
    permissions:
      contents: write
      packages: write

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Lint code
      - name: Lint code
        run: npm run lint

      # 5. Run tests and collect coverage
      - name: Run tests and collect coverage
        env:
          ROKU_DEV_TARGET: ${{ secrets.ROKU_DEV_TARGET }}
          ROKU_DEV_PASS: ${{ secrets.ROKU_DEV_PASS }}
        run: npm run collect-coverage

      # 5b. Fix coverage file paths (.brs → .bs, remove generated files)
      - name: Fix coverage file paths
        run: node scripts/fix-coverage-paths.js

      # 6. Upload coverage to Coveralls
      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: coverage.lcov
          base-path: src

      # 7. Create source package (ZIP with raw .bs files)
      - name: Create source package
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          rm -f out/rotor-framework.zip
          mkdir -p out/rotor-framework-package
          cp -r src/source/* out/rotor-framework-package/
          rm -rf out/rotor-framework-package/tests
          rm -f out/rotor-framework-package/Main.brs
          node scripts/prepare-source-readme.js README.md out/rotor-framework-package/README.md
          cp LICENSE.md out/rotor-framework-package/
          cd out/rotor-framework-package
          zip -r ../rotor-framework.zip . -x "*.spec.bs" "*.DS_Store"
          cd ../..
          rm -rf out/rotor-framework-package

      # 8. Create GitHub Release and upload package
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: out/rotor-framework.zip
          generate_release_notes: true
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build source package for npm
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          npm ci
          npm run build
          npm pack
          ls -lh *.tgz

      - name: Publish to npm
        if: startsWith(github.ref, 'refs/tags/')
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
