import "pkg:/components/tests/dispatcherTest/DispatcherTest.const.bs"

namespace test

    class TestModel extends Model
        state = {
            foo: "bar",
            hitCounter: 0
        }
    end class

    class TestReducer extends Reducer

        override function applyMiddlewares()
            return [
                function(intent, state) as Intent

                    if intent.type = IntentTypes.BLOCK_BY_MIDDLEWARE
                        return invalid
                    end if

                    return intent ' NEXT
                end function

            ]
        end function

        override function reducer(state, intent)

            if intent.type = IntentTypes.UPDATE_FOO
                state.foo = intent.payload.foo
                state.hitCounter++
            end if

            return state
        end function
    end class

    function createFooDispatcher() as Rotor.Dispatcher
        ' Create the fooDispatcher instance (first argument defines the global dispatcher key)
        return Rotor.createDispatcher("fooDispatcher", new test.TestModel(), new test.TestReducer())
    end function


end namespace

